site_name: Introduction to Scientific Visualization with ParaView
site_url: https://surf-visualization.github.io/paraview-course

theme:
  name: material
  custom_dir: theme_overrides
  features:
    - navigation.tabs   
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.top
    - navigation.footer    
  logo: images/surf-logo.svg
  favicon: images/favicon.png
  
extra_css:
  - extra.css
  
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://social.edu.nl/@SURF/

markdown_extensions:
  - admonition    
  - codehilite
  - tables  
  - toc:
      permalink: True
      toc_depth : "1-3"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  # For image attributes
  - pymdownx.magiclink
  - attr_list
  - markdown_captions       # https://pypi.org/project/markdown-captions/
  - footnotes
  - sane_lists
     
plugins:
  - search
  - git-revision-date-localized:
      #type: datetime
      type: custom
      custom_format: "%d %B %Y %H:%M:%S"      
      timezone: Europe/Amsterdam

# Input dir will be searched for *.md files
docs_dir: docs

# Output location for `mkdocs build`. Will remove complete dir on rebuild!
site_dir: site

# Navigation structure, basically left-side menu
nav:
  - index.md
  - preparation.md
  - Exercises:
    - exercise1.md
    - exercise2.md
    - exercise3.md
    - bonus.md
  - appearance.md
  - scripting.md
  - miscellaneous.md
  #- privacy.md
    
copyright: Copyright &copy; 2018-2025 SURF
