name: ci 

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install \
            mkdocs-material \
            mkdocs-material-extensions \
            mkdocs-enumerate-headings-plugin \
            mkdocs-add-number-plugin \
            pymdown-extensions \
            markdown-captions
      - run: mkdocs gh-deploy --force
